apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: webserver
  labels:
    app: flask-mysql-app
spec:
  destination:
    namespace: webserver
  selector:
    name: flask-app-pod
  type: NodePort
  ports:
    - name: http-port
      port: 8080
      targetPort: 5000
      nodePort: 31000
