apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-app
  namespace: webserver
data:
  PASSWORD: password
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_HOST: mysql-service:3306
  SECRET_KEY: secret

